/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.View;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author ACER
 */
public class fHomePageQLK extends javax.swing.JFrame {
    private CardLayout cardLayout;
    
    private pDonHang pDonHang;
    private pNguyenVatLieu pNguyenVatLieu;
    private pNhapSanPham pNhapSanPham;
    
    public fHomePageQLK() {
        
        initComponents();
        setLocationRelativeTo(null);
        setupCardLayout();
        addSubPanel();
        setupMenu();
    }
    
    public void setupCardLayout(){
        cardLayout = new CardLayout();
        mainpanel.setLayout(cardLayout);
    }
    
    public void addSubPanel(){
        
         pNhapSanPham = new pNhapSanPham();
        mainpanel.add(pNhapSanPham, "QuanLySp");
        
        
         pNguyenVatLieu = new pNguyenVatLieu();
        mainpanel.add(pNguyenVatLieu, "QuanLyNvl");
        
        pDonHang = new pDonHang();
        mainpanel.add(pDonHang, "QuanLyDonHang");

       

      
    }
    
    private void setupMenu() {
        JMenuBar menuBar = new JMenuBar();

        // Tạo menu và các mục trong menu
        JMenu menuQuanLy = new JMenu("Quản Lý");
        
                
        JMenuItem menuItemSp = new JMenuItem("Quản Lý Sản Phẩm");
        menuItemSp.addActionListener(e -> showPanel("QuanLySp"));
        
        JMenuItem menuItemNvl = new JMenuItem("Quản lý Nguyên Vật Liệu");
        menuItemNvl.addActionListener(e -> showPanel("QuanLyNvl"));

        JMenuItem menuItemDonHang = new JMenuItem("Quản lý Đơn Hàng");
        menuItemDonHang.addActionListener(e -> showPanel("QuanLyDonHang"));
        
        
        
        // Thêm các mục vào menu
        menuQuanLy.add(menuItemSp);
        menuQuanLy.add(menuItemNvl);
        menuQuanLy.add(menuItemDonHang);
        

        // Thêm menu vào thanh menu
        menuBar.add(menuQuanLy);

        // Thiết lập thanh menu cho JFrame
        setJMenuBar(menuBar);
    }
    
    // Phương thức chuyển đổi panel trong mainpanel
    private void showPanel(String panelName) {
            cardLayout.show(mainpanel, panelName);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);

        mainpanel.setMinimumSize(new java.awt.Dimension(862, 757));
        mainpanel.setPreferredSize(new java.awt.Dimension(862, 757));
        mainpanel.setVerifyInputWhenFocusTarget(false);
        mainpanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
