/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.View;

import com.mycompany.Controller.QuanLyBaoHiemController;
import com.mycompany.Controller.QuanLyHoSoController;
import com.mycompany.Model.DanhSachBaoHiemModel;
import com.mycompany.Model.QuanLyBaoHiemModel;
import com.mycompany.Model.QuanLyHoSoModel;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class pQuanLyBaoHiem extends javax.swing.JPanel {
    private QuanLyHoSoModel quanLyHoSoModel;
    private QuanLyBaoHiemModel quanLyBaoHiemModel;
    private QuanLyBaoHiemController quanLyBaoHiemController;
    private DanhSachBaoHiemModel danhSachBaoHiemModel;
    /**
     * Creates new form pQuanLyBaoHiem
     */
    public pQuanLyBaoHiem() {
        initComponents();
        quanLyBaoHiemController = new QuanLyBaoHiemController(this);
        quanLyHoSoModel = new QuanLyHoSoModel();
        quanLyBaoHiemModel = new QuanLyBaoHiemModel();
        danhSachBaoHiemModel= new DanhSachBaoHiemModel();
        addDataToComboBox();
        addDataToComboBox2();
    }
    
    private void addDataToComboBox() {
        List<Object[]> danhSachNhanVien = quanLyHoSoModel.danhSachHoSoNV();
        
        jComboBox_MaNhanVien.removeAllItems();
        
        for (Object[] nhanVien : danhSachNhanVien) {
            String tenNhanVien = nhanVien[0].toString() + " - " + nhanVien[1].toString();
            jComboBox_MaNhanVien.addItem(tenNhanVien);
        }
    }
    
    private void addDataToComboBox2() {
       // List<Object[]> danhsachBaoHiem = quanLyBaoHiemModel.getThongTinBaoHiemNhanVien();
        List<Object[]> danhsachBaoHiem = danhSachBaoHiemModel.danhSachBaoHiem();
        
        jComboBox_mabaohiem.removeAllItems();
        
        for (Object[] baoHiem : danhsachBaoHiem) {
            String tenBaoHiem = baoHiem[0].toString() + " - " + baoHiem[1].toString();
            jComboBox_mabaohiem.addItem(tenBaoHiem);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_QLBaoHiem = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_ThemBH = new javax.swing.JButton();
        jButton_XoaBH = new javax.swing.JButton();
        jComboBox_MaNhanVien = new javax.swing.JComboBox<>();
        jComboBox_mabaohiem = new javax.swing.JComboBox<>();
        jButton_chuyendsbh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable_QLBaoHiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_QLBaoHiem);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã Nhân viên :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ BẢO HIỂM");
        jLabel1.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã bảo hiểm :");

        jButton_ThemBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_ThemBH.setText("Thêm");
        jButton_ThemBH.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jButton_ThemBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ThemBHMouseClicked(evt);
            }
        });

        jButton_XoaBH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_XoaBH.setText("Xóa");
        jButton_XoaBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_XoaBHMouseClicked(evt);
            }
        });

        jComboBox_MaNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jButton_chuyendsbh.setText("Danh sách bảo hiểm");
        jButton_chuyendsbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_chuyendsbhMouseClicked(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jButton_ThemBH)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton_XoaBH))
                            .addComponent(jComboBox_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_mabaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(jButton_chuyendsbh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(82, 82, 82)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_mabaohiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton_chuyendsbh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_XoaBH)
                    .addComponent(jButton_ThemBH))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_chuyendsbhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_chuyendsbhMouseClicked
        // Tạo đối tượng panel pDanhSachBaoHiem
        pDanhSachBaoHiem pBaoHiem = new pDanhSachBaoHiem();

        // Tạo JFrame mới để chứa panel
        JFrame frame = new JFrame("Danh Sách Bảo Hiểm");

        // Thêm panel pBaoHiem vào JFrame
        frame.add(pBaoHiem);

        // Thiết lập kích thước và các thuộc tính của JFrame
        frame.setSize(700, 500); // Đặt kích thước cửa sổ
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Đóng cửa sổ nhưng không thoát ứng dụng
        frame.setLocationRelativeTo(null); // Đặt cửa sổ xuất hiện ở giữa màn hình

        // Hiển thị JFrame
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_chuyendsbhMouseClicked

    private void jButton_ThemBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ThemBHMouseClicked
        // Lấy chuỗi được chọn từ jComboBox_MaNhanVien và jComboBox_mabaohiem
        String selectedNhanVien = (String) jComboBox_MaNhanVien.getSelectedItem();
        String selectedBaoHiem = (String) jComboBox_mabaohiem.getSelectedItem();

        // Tách chuỗi để lấy phần mã (phần trước dấu '-')
        String maNV = selectedNhanVien.split(" - ")[0];
        String maBH = selectedBaoHiem.split(" - ")[0];
        
        String result = quanLyBaoHiemController.addBaoHiem(maNV, maBH);

        // Hiển thị thông báo kết quả
        JOptionPane.showMessageDialog(this, result);
        
        quanLyBaoHiemController.refreshDataTable();
    }//GEN-LAST:event_jButton_ThemBHMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // Mở trang Home
    Home home = new Home();
    home.setVisible(true);

    // Đóng JFrame hiện tại chứa JPanel này
    java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();  // Đóng cửa sổ hiện tại
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_XoaBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_XoaBHMouseClicked
       // Lấy mã nhân viên và mã bảo hiểm được chọn từ combo box
    String selectedNhanVien = (String) jComboBox_MaNhanVien.getSelectedItem();
    String selectedBaoHiem = (String) jComboBox_mabaohiem.getSelectedItem();

    // Tách chuỗi để lấy phần mã (phần trước dấu '-')
    String maNV = selectedNhanVien.split(" - ")[0];
    String maBH = selectedBaoHiem.split(" - ")[0];

    // Xác nhận người dùng có chắc chắn muốn xóa
    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa thông tin bảo hiểm này?", "Xác nhận", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // Gọi phương thức xóa bảo hiểm trong Controller
        boolean result = quanLyBaoHiemController.deleteBaoHiem(maNV, maBH);

        if (result) {
            JOptionPane.showMessageDialog(this, "Xóa thông tin bảo hiểm thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thông tin bảo hiểm thất bại!");
        }

        // Làm mới bảng dữ liệu
        quanLyBaoHiemController.refreshDataTable();
    }
    }//GEN-LAST:event_jButton_XoaBHMouseClicked
    
      
//    public JButton getjButton_SuaBH() {
//        return jButton_SuaBH;
//    }

    public JButton getjButton_ThemBH() {
        return jButton_ThemBH;
    }

    public JButton getjButton_XoaBH() {
        return jButton_XoaBH;
    }

    public JTable getjTable_QLBaoHiem() {
        return jTable_QLBaoHiem;
    }
    
  

    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_ThemBH;
    private javax.swing.JButton jButton_XoaBH;
    private javax.swing.JButton jButton_chuyendsbh;
    private javax.swing.JComboBox<String> jComboBox_MaNhanVien;
    private javax.swing.JComboBox<String> jComboBox_mabaohiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_QLBaoHiem;
    // End of variables declaration//GEN-END:variables
}
