/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.View;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author mihvu
 */
public class PdatDonHang extends javax.swing.JPanel {

    /**
     * Creates new form PdatDonHang
     */
    public PdatDonHang() {
        initComponents();
    }

    public JButton getjButton_CapNhatDH() {
        return jButton_CapNhatDH;
    }

    public JButton getjButton_TaoDH() {
        return jButton_TaoDH;
    }

    public JButton getjButton_XoaDH() {
        return jButton_XoaDH;
    }

    public JButton getjButton_timKhiemDH() {
        return jButton_timKhiemDH;
    }
    public void setMaDH1(String value) {
        jTextField_MaDH1.setText(value);
    }

    public String getMaDH1() {
        return jTextField_MaDH1.getText().trim();
    }

    // Getter and Setter for jTextField_TimKiemDH
    public void setTimKiemDH(String value) {
        jTextField_TimKiemDH.setText(value);
    }

    public String getTimKiemDH() {
        return jTextField_TimKiemDH.getText().trim();
    }

    public JTable getjTable_chiTietDH() {
        return jTable_chiTietDH;
    }

    public JTable getjTable_chitietDH() {
        return jTable_chitietDH;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_TimKiemDH = new javax.swing.JTextField();
        jButton_timKhiemDH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_chitietDH = new javax.swing.JTable();
        jButton_TaoDH = new javax.swing.JButton();
        jButton_CapNhatDH = new javax.swing.JButton();
        jButton_XoaDH = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_MaDH1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_chiTietDH = new javax.swing.JTable();

        setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButton_timKhiemDH.setText("TÌM KIẾM");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH ĐẶT ĐƠN HÀNG");

        jTable_chitietDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Tên KH", "Ngày dặt", "Ngày giao", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(jTable_chitietDH);

        jButton_TaoDH.setText("Tạo đơn hàng mới");

        jButton_CapNhatDH.setText("Cập nhật đơn hàng");

        jButton_XoaDH.setText("Xóa đơn hàng ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("CHI TIẾT ĐƠN ĐẶT HÀNG");

        jTable_chiTietDH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Số lượng đặt"
            }
        ));
        jScrollPane2.setViewportView(jTable_chiTietDH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(jTextField_MaDH1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextField_TimKiemDH, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton_timKhiemDH, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_CapNhatDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TaoDH)
                            .addComponent(jButton_XoaDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TimKiemDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timKhiemDH))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_TaoDH)
                        .addGap(39, 39, 39)
                        .addComponent(jButton_CapNhatDH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_XoaDH))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_MaDH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CapNhatDH;
    private javax.swing.JButton jButton_TaoDH;
    private javax.swing.JButton jButton_XoaDH;
    private javax.swing.JButton jButton_timKhiemDH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_chiTietDH;
    private javax.swing.JTable jTable_chitietDH;
    private javax.swing.JTextField jTextField_MaDH1;
    private javax.swing.JTextField jTextField_TimKiemDH;
    // End of variables declaration//GEN-END:variables
}
