/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.View;

import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author mihvu
 */
public class PtaoDonHang extends javax.swing.JPanel {

    /**
     * Creates new form PtaoDonHang
     */
    public PtaoDonHang() {
        initComponents();
    }

    public JButton getjButton_Taodon() {
        return jButton_Taodon;
    }

    public JButton getjButton_TimKH() {
        return jButton_TimKH;
    }

    public JButton getjButton_TimMatHang() {
        return jButton_TimMatHang;
    }

    public JComboBox<String> getjComboBox_NVBH() {
        return jComboBox_NVBH;
    }

    public JTable getjTable_danhSachDaThem() {
        return jTable_danhSachDaThem;
    }

    public JTable getjTable_thongMatHang2() {
        return jTable_thongMatHang2;
    }

    public JButton getjButton_hoanThanh() {
        return jButton_hoanThanh;
    }

    public JTable getjTable_thongTinKH() {
        return jTable_thongTinKH;
    }

        // Getter and Setter for jTextField_TimKH
    public void setTimKH(String value) {
        jTextField_TimKH.setText(value);
    }

    public String getTimKH() {
        return jTextField_TimKH.getText().trim();
    }

    // Getter and Setter for jTextField_chonMatHang
    public void setChonMatHang(String value) {
        jTextField_chonMatHang.setText(value);
    }

    public String getChonMatHang() {
        return jTextField_chonMatHang.getText().trim();
    }

    // Getter and Setter for jTextField_maDH
    public void setMaDH(String value) {
        jTextField_maDH.setText(value);
    }

    public String getMaDH() {
        return jTextField_maDH.getText().trim();
    }

    // Getter and Setter for jTextField_maKH2
    public void setMaKH2(String value) {
        jTextField_maKH2.setText(value);
    }

    public String getMaKH2() {
        return jTextField_maKH2.getText().trim();
    }

    // Getter and Setter for jTextField_maMH
    public void setMaMH(String value) {
        jTextField_maMH.setText(value);
    }

    public String getMaMH() {
        return jTextField_maMH.getText().trim();
    }

    // Getter and Setter for jTextField_tenMH
    public void setTenMH(String value) {
        jTextField_tenMH.setText(value);
    }

    public String getTenMH() {
        return jTextField_tenMH.getText().trim();
    }

    // Getter and Setter for jTextField_soLuongMH
    public void setSoLuongMH(String value) {
        jTextField_soLuongMH.setText(value);
    }

    public String getSoLuongMH() {
        return jTextField_soLuongMH.getText().trim();
    }
    // Setter for jDateChooser_ngayGiao
    public void setValueJDateChooserngayGiao(Date value) {
        jDateChooser_ngayGiao.setDate(value);
    }

    // Getter for jDateChooser_ngayGiao
    public Date getValueJDateChooserngayGiao() {
        return jDateChooser_ngayGiao.getDate();
    }

    // Setter for jDateChooser_ngayDat
    public void setValueJDateChooserngayDat(Date value) {
        jDateChooser_ngaydat.setDate(value);
    }

    // Getter for jDateChooser_ngayDat
    public Date getValueJDateChooserngayDat() {
        return jDateChooser_ngaydat.getDate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_TimKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton_TimKH = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_thongTinKH = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField_chonMatHang = new javax.swing.JTextField();
        jButton_TimMatHang = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_thongMatHang2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_maMH = new javax.swing.JTextField();
        jTextField_tenMH = new javax.swing.JTextField();
        jTextField_soLuongMH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_maKH2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_maDH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_danhSachDaThem = new javax.swing.JTable();
        jButton_Taodon = new javax.swing.JButton();
        jComboBox_NVBH = new javax.swing.JComboBox<>();
        jButton_hoanThanh = new javax.swing.JButton();
        jDateChooser_ngaydat = new com.toedter.calendar.JDateChooser();
        jDateChooser_ngayGiao = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tạo đơn hàng");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Chọn khách hàng");

        jButton_TimKH.setText("Tìm");

        jTable_thongTinKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(jTable_thongTinKH);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Chọn mặt hàng");

        jButton_TimMatHang.setText("Tìm");

        jTable_thongMatHang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã MH", "Tên HN", "Tồn kho"
            }
        ));
        jScrollPane2.setViewportView(jTable_thongMatHang2);

        jLabel4.setText("Mã mặt hàng");

        jLabel5.setText("Tên mặt hàng");

        jLabel6.setText("Số  lượng mặt ");

        jLabel7.setText("Mã khách hàng");

        jLabel8.setText("Mã đơn hàng");

        jLabel9.setText("Ngày đặt");

        jLabel10.setText("Ngày giao");

        jLabel11.setText("NVBH");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("DANH SÁCH MẶT HÀNG ĐÃ THÊM");

        jTable_danhSachDaThem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã mặt hàng", "Tên mặt hàng", "Số lượng đặt"
            }
        ));
        jScrollPane3.setViewportView(jTable_danhSachDaThem);

        jButton_Taodon.setText("Tạo đơn");

        jComboBox_NVBH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton_hoanThanh.setText("Hoàn thành");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_hoanThanh))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(jTextField_maMH))
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_TimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton_TimKH))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_chonMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_TimMatHang))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_soLuongMH)
                                    .addComponent(jTextField_tenMH))))
                        .addGap(40, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_maKH2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_Taodon))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_maDH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_NVBH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_ngaydat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser_ngayGiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TimKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimKH))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_maKH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_maDH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jDateChooser_ngaydat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser_ngayGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox_NVBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_chonMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TimMatHang)
                    .addComponent(jLabel12)
                    .addComponent(jButton_Taodon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_tenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_soLuongMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_hoanThanh)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Taodon;
    private javax.swing.JButton jButton_TimKH;
    private javax.swing.JButton jButton_TimMatHang;
    private javax.swing.JButton jButton_hoanThanh;
    private javax.swing.JComboBox<String> jComboBox_NVBH;
    private com.toedter.calendar.JDateChooser jDateChooser_ngayGiao;
    private com.toedter.calendar.JDateChooser jDateChooser_ngaydat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_danhSachDaThem;
    private javax.swing.JTable jTable_thongMatHang2;
    private javax.swing.JTable jTable_thongTinKH;
    private javax.swing.JTextField jTextField_TimKH;
    private javax.swing.JTextField jTextField_chonMatHang;
    private javax.swing.JTextField jTextField_maDH;
    private javax.swing.JTextField jTextField_maKH2;
    private javax.swing.JTextField jTextField_maMH;
    private javax.swing.JTextField jTextField_soLuongMH;
    private javax.swing.JTextField jTextField_tenMH;
    // End of variables declaration//GEN-END:variables
}
