/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.View;

import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author ACER
 */
public class fHomePageQLSX extends javax.swing.JFrame {
    private CardLayout cardLayout;
    
    private pDanhSachNVL panelDanhSachNVL;
    private pDanhSachSP panelDanhSachSP;
    private pDanhSachYeuCau panelDanhSachYeuCau;
    private pNghiemThu panelNghiemThu;
    private pQuanLyLoSP panelLoSP;
    
    public fHomePageQLSX() {
        
        initComponents();
        setLocationRelativeTo(null);
        setupCardLayout();
        addSubPanel();
        setupMenu();
    }
    
    public void setupCardLayout(){
        cardLayout = new CardLayout();
        mainpanel.setLayout(cardLayout);
    }
    
    public void addSubPanel(){
        panelDanhSachNVL = new pDanhSachNVL();
        mainpanel.add(panelDanhSachNVL, "QuanLyNvl");

        panelDanhSachSP = new pDanhSachSP();
        mainpanel.add(panelDanhSachSP, "QuanLySp");

        panelDanhSachYeuCau = new pDanhSachYeuCau();
        mainpanel.add(panelDanhSachYeuCau, "QuanLyYeuCau");

        panelNghiemThu = new pNghiemThu();
        mainpanel.add(panelNghiemThu, "QuanLyNghiemThu");
        
        panelLoSP = new pQuanLyLoSP();
        mainpanel.add(panelLoSP, "QuanLyLoSp");
    }
    
    private void setupMenu() {
        JMenuBar menuBar = new JMenuBar();

        // Tạo menu và các mục trong menu
        JMenu menuQuanLy = new JMenu("Quản Lý");
        
        JMenuItem menuItemNvl = new JMenuItem("Nguyên vật liệu");
        menuItemNvl.addActionListener(e -> showPanel("QuanLyNvl"));
        
        JMenuItem menuItemSp = new JMenuItem("Sản phẩm");
        menuItemSp.addActionListener(e -> showPanel("QuanLySp"));
        
        JMenuItem menuItemYcsx = new JMenuItem("Yêu cầu sản xuất");
        menuItemYcsx.addActionListener(e -> showPanel("QuanLyYeuCau"));
        
        JMenuItem menuItemNghiemThu = new JMenuItem("Nghiệm thu");
        menuItemNghiemThu.addActionListener(e -> showPanel("QuanLyNghiemThu"));
        
        JMenuItem menuItemLoSp = new JMenuItem("Lô sản phẩm");
        menuItemLoSp.addActionListener(e -> showPanel("QuanLyLoSp"));
        
        // Thêm các mục vào menu
        menuQuanLy.add(menuItemNvl);
        menuQuanLy.add(menuItemSp);
        menuQuanLy.add(menuItemYcsx);
        menuQuanLy.add(menuItemNghiemThu);
        menuQuanLy.add(menuItemLoSp);

        // Thêm menu vào thanh menu
        menuBar.add(menuQuanLy);

        // Thiết lập thanh menu cho JFrame
        setJMenuBar(menuBar);
    }
    
    // Phương thức chuyển đổi panel trong mainpanel
    private void showPanel(String panelName) {
            cardLayout.show(mainpanel, panelName);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);

        mainpanel.setMinimumSize(new java.awt.Dimension(862, 757));
        mainpanel.setPreferredSize(new java.awt.Dimension(862, 757));
        mainpanel.setVerifyInputWhenFocusTarget(false);
        mainpanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
