/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.View;

import com.mycompany.Controller.PhieuNghiemThuController;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class pTaoPhieuNghiemTHu extends javax.swing.JPanel {

    /**
     * Creates new form pTaoPhieuNghiemTHu
     */
    public pTaoPhieuNghiemTHu() {
        initComponents();
        PhieuNghiemThuController phieuNghiemThuController = new PhieuNghiemThuController(this);
        jButton_nghiemthu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ycsx = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_canNghiemThu = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_daNghiemThu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_phieuyeucau = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_maphieuyeucau = new javax.swing.JTextField();
        jTextField_maphieunghiemthu = new javax.swing.JTextField();
        jTextField_noidung = new javax.swing.JTextField();
        jDateChooser_ngaynghiemthu = new com.toedter.calendar.JDateChooser();
        jButton_taophieu = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_solo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_ketquanghiemthu = new javax.swing.JTextArea();
        jButton_nghiemthu = new javax.swing.JButton();
        jButton_hoanthnah = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTable_ycsx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Sl cần sản xuất"
            }
        ));
        jScrollPane1.setViewportView(jTable_ycsx);

        jTable_canNghiemThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Số lô", "Mã Sp", "SL sản phẩm", "NSX", "Tình trạng"
            }
        ));
        jScrollPane2.setViewportView(jTable_canNghiemThu);

        jTable_daNghiemThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "YCSX", "Số lô", "Tên sản phẩm", "Kết quả NT"
            }
        ));
        jScrollPane3.setViewportView(jTable_daNghiemThu);

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TẠO PHIẾU NGHIỆM THU");
        jLabel1.setOpaque(true);

        jLabel2.setText("Phiếu yêu cầu sản xuất");

        jLabel3.setText("Mã phiếu YCSX");

        jLabel4.setText("Mã phiếu nghiệm thu");

        jLabel5.setText("Nội dung");

        jLabel6.setText("Ngày nghiệm thu");

        jButton_taophieu.setBackground(new java.awt.Color(0, 153, 255));
        jButton_taophieu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_taophieu.setText("Tạo phiếu nghiệm thu");
        jButton_taophieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_taophieuActionPerformed(evt);
            }
        });

        jLabel7.setText("Danh sách số lô sản phẩm cần nghiệm thu");

        jLabel8.setText("Danh sách số lô sản phẩm đã được nghiệm thu");

        jLabel9.setText("Số lô");

        jLabel10.setText("KQ nghiệm thu");

        jTextArea_ketquanghiemthu.setColumns(20);
        jTextArea_ketquanghiemthu.setRows(5);
        jScrollPane4.setViewportView(jTextArea_ketquanghiemthu);

        jButton_nghiemthu.setBackground(new java.awt.Color(0, 153, 255));
        jButton_nghiemthu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_nghiemthu.setText("Nghiệm thu");

        jButton_hoanthnah.setBackground(new java.awt.Color(0, 153, 255));
        jButton_hoanthnah.setForeground(new java.awt.Color(255, 255, 255));
        jButton_hoanthnah.setText("Hoàn thành");
        jButton_hoanthnah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hoanthnahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(jComboBox_phieuyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(52, 52, 52)
                                            .addComponent(jTextField_solo)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(50, 50, 50)
                                                    .addComponent(jTextField_maphieuyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField_maphieunghiemthu)
                                                        .addComponent(jTextField_noidung)
                                                        .addComponent(jDateChooser_ngaynghiemthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addComponent(jButton_taophieu, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(16, 16, 16))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton_hoanthnah)
                                            .addGap(21, 21, 21)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_nghiemthu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_phieuyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_solo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_nghiemthu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_maphieuyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_maphieunghiemthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_noidung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser_ngaynghiemthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton_taophieu)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_hoanthnah)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_hoanthnahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hoanthnahActionPerformed
        setMaPhieuNghiemThu("");
        setMaPhieuYeuCau("");
        setNoiDung("");
        setValueJDateChooser(null);
        setSoLo("");
        setKetQuaNghiemThu("");
        jButton_nghiemthu.setEnabled(false);
        jTextField_maphieunghiemthu.setEnabled(true);
        jTextField_maphieuyeucau.setEnabled(true);
        jTextField_noidung.setEnabled(true);
        jDateChooser_ngaynghiemthu.setEnabled(true);
        jButton_taophieu.setEnabled(true);
    }//GEN-LAST:event_jButton_hoanthnahActionPerformed

    private void jButton_taophieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_taophieuActionPerformed
        jTextField_maphieunghiemthu.setEnabled(false);
        jTextField_maphieuyeucau.setEnabled(false);
        jTextField_noidung.setEnabled(false);
        jDateChooser_ngaynghiemthu.setEnabled(false);
        jButton_taophieu.setEnabled(false);
        jButton_nghiemthu.setEnabled(true);
    }//GEN-LAST:event_jButton_taophieuActionPerformed
    
    public JButton getjButton_hoanthnah() {
        return jButton_hoanthnah;
    }

    public void setValueJDateChooser(Date value) {
            jDateChooser_ngaynghiemthu.setDate(value);
        }

        public Date getValueJDateChooser() {
             java.util.Date utilDate = jDateChooser_ngaynghiemthu.getDate();
            return new Date(utilDate.getTime());
        }
    
    public JButton getjButton_nghiemthu() {
        return jButton_nghiemthu;
    }

    public JButton getjButton_taophieu() {
        return jButton_taophieu;
    }

    public JComboBox<String> getjComboBox_phieuyeucau() {
        return jComboBox_phieuyeucau;
    }

    public JTable getjTable1() {
        return jTable_ycsx;
    }

    public JTable getjTable2() {
        return jTable_canNghiemThu;
    }

    public JTable getjTable3() {
        return jTable_daNghiemThu;
    }
    public void setKetQuaNghiemThu(String value) {
    jTextArea_ketquanghiemthu.setText(value);
}

public String getKetQuaNghiemThu() {
    return jTextArea_ketquanghiemthu.getText().trim();
}

public void setMaPhieuNghiemThu(String value) {
    jTextField_maphieunghiemthu.setText(value);
}

public String getMaPhieuNghiemThu() {
    return jTextField_maphieunghiemthu.getText().trim();
}

public void setMaPhieuYeuCau(String value) {
    jTextField_maphieuyeucau.setText(value);
}

public String getMaPhieuYeuCau() {
    return jTextField_maphieuyeucau.getText().trim();
}

public void setNoiDung(String value) {
    jTextField_noidung.setText(value);
}

public String getNoiDung() {
    return jTextField_noidung.getText().trim();
}

public void setSoLo(String value) {
    jTextField_solo.setText(value);
}

public String getSoLo() {
    return jTextField_solo.getText().trim();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_hoanthnah;
    private javax.swing.JButton jButton_nghiemthu;
    private javax.swing.JButton jButton_taophieu;
    private javax.swing.JComboBox<String> jComboBox_phieuyeucau;
    private com.toedter.calendar.JDateChooser jDateChooser_ngaynghiemthu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_canNghiemThu;
    private javax.swing.JTable jTable_daNghiemThu;
    private javax.swing.JTable jTable_ycsx;
    private javax.swing.JTextArea jTextArea_ketquanghiemthu;
    private javax.swing.JTextField jTextField_maphieunghiemthu;
    private javax.swing.JTextField jTextField_maphieuyeucau;
    private javax.swing.JTextField jTextField_noidung;
    private javax.swing.JTextField jTextField_solo;
    // End of variables declaration//GEN-END:variables
}
