/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.QLSX.View;
import com.mycompany.QLSX.Controller.NguyenVatLieuController;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Admin
 */
public class pDanhSachNVL extends javax.swing.JPanel {

    /**
     * Creates new form pDanhSachNVL
     */
    public pDanhSachNVL() {
        initComponents();
        NguyenVatLieuController nguyenVatLieuController = new NguyenVatLieuController(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_timkiem = new javax.swing.JTextField();
        jButton_timkiem = new javax.swing.JButton();
        jButton_them = new javax.swing.JButton();
        jButton_sua = new javax.swing.JButton();
        jButton_xoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_danhSachNVL = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_manvl = new javax.swing.JTextField();
        jTextField_tennvl = new javax.swing.JTextField();
        jTextField_ghichu = new javax.swing.JTextField();
        jButton_quaylai = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton_timkiem.setBackground(new java.awt.Color(0, 153, 255));
        jButton_timkiem.setForeground(new java.awt.Color(255, 255, 255));
        jButton_timkiem.setText("Tìm Kiếm");

        jButton_them.setBackground(new java.awt.Color(0, 153, 255));
        jButton_them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_them.setForeground(new java.awt.Color(255, 255, 255));
        jButton_them.setText("Thêm mới");

        jButton_sua.setBackground(new java.awt.Color(0, 153, 255));
        jButton_sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_sua.setForeground(new java.awt.Color(255, 255, 255));
        jButton_sua.setText("Cập nhật thông tin");

        jButton_xoa.setBackground(new java.awt.Color(0, 153, 255));
        jButton_xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_xoa.setForeground(new java.awt.Color(255, 255, 255));
        jButton_xoa.setText("Xóa");

        jLabel1.setText("DANH SÁCH NGUYÊN VẬT LIỆU");

        jTable_danhSachNVL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã NVL", "Tên nguyên vật liệu", "Ghi chú"
            }
        ));
        jScrollPane1.setViewportView(jTable_danhSachNVL);

        jLabel2.setText("Mã nguyên vật liệu");

        jLabel3.setText("Tên nguyên vật liệu ");

        jLabel4.setText("Ghi chú");

        jButton_quaylai.setBackground(new java.awt.Color(0, 153, 255));
        jButton_quaylai.setForeground(new java.awt.Color(255, 255, 255));
        jButton_quaylai.setText("Quay Lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_timkiem)))
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(34, 34, 34)
                                .addComponent(jTextField_manvl))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_ghichu)
                                    .addComponent(jTextField_tennvl))))
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton_quaylai))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_timkiem)
                    .addComponent(jButton_quaylai))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_them, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_manvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_tennvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButton_sua() {
        return jButton_sua;
    }

    public JButton getjButton_quaylai() {
        return jButton_quaylai;
    }

    
    
    public JButton getjButton_them() {
        return jButton_them;
    }

    public JButton getjButton_timkiem() {
        return jButton_timkiem;
    }

    public JButton getjButton_xoa() {
        return jButton_xoa;
    }

    public JTable getjTable_danhSachNVL() {
        return jTable_danhSachNVL;
    }
    public void setGhiChu(String value) {
    jTextField_ghichu.setText(value);
}

public String getGhiChu() {
    return jTextField_ghichu.getText().trim();
}

public void setMaNVL(String value) {
    jTextField_manvl.setText(value);
}

public String getMaNVL() {
    return jTextField_manvl.getText().trim();
}

public void setTenNVL(String value) {
    jTextField_tennvl.setText(value);
}

public String getTenNVL() {
    return jTextField_tennvl.getText().trim();
}

public void setTimKiem(String value) {
    jTextField_timkiem.setText(value);
}

public String getTimKiem() {
    return jTextField_timkiem.getText().trim();
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_quaylai;
    private javax.swing.JButton jButton_sua;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_timkiem;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_danhSachNVL;
    private javax.swing.JTextField jTextField_ghichu;
    private javax.swing.JTextField jTextField_manvl;
    private javax.swing.JTextField jTextField_tennvl;
    private javax.swing.JTextField jTextField_timkiem;
    // End of variables declaration//GEN-END:variables
}
